name: swcast
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas=2.2.*
  - numpy=1.26.*
  - pyarrow=16.*
  - requests=2.32.*
  - pyyaml=6.0.*
  - matplotlib=3.9.*
  - scipy=1.13.*
  - pytest=8.*
  - xarray=2024.*
  - netcdf4=1.6.*
  - pip=24.*
  - pip:
      - opentimestamps-client==0.7.1
